baseURL = 'https://tonybailey.dev/'
languageCode = 'en-us'
title = 'Tony Bailey'
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
 [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"
#    weight = 3
#  [[menu.main]]
#    identifier = "posts"
#    name = "Posts"
#    url = "/posts/"
#    weight = 4

[params]
  author = "Tony Bailey"
  description = "A developer"
  avatar = "/images/tony.jpeg"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/tonybaileydev"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/tonybaileydev"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/tonybaileydev"
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:tony@tonybailey.dev"

[taxonomies]
  tag = "tags"

  [params.style]
    darkestColor = "#ffffff"
    darkColor = "#ffffff"
    lightColor = "#000000"
    lightestColor = "#000000"
    primaryColor = "#000000"

  # Orangey
  #[params.style]
  #  darkestColor = "#dd6e42"
  #  darkColor = "#4f6d7a"
  #  lightColor = "#c0d6df"
  #  lightestColor = "#eaeaea"
  #  primaryColor = "#e8dab2"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
